### ISSUE TITLE
Support ObjectId _id's for collections

### ISSUE THREAD

**Issue by samoilis** [cult-of-coders/grapher#113]
Hi 

this awesome library can be work with Mongo ObjectId (24 digit hex string) in the key Fields?
maybe I've something missed out :(

I've try the same simple test code with strings and ObjectIDs in the Key Field (in the sample 'joinId') and in the second case return me only data from the primary collection (Col1). I've try also different declarations in simpleSchema object with the same result

Also I use Mongodb 3.4.2 outside of Meteor

---

**Collections:**
```javascript
import { Col1Schema } from './schema.js';
const Col1 = new Mongo.Collection("col1");
      Col1.attachSchema(Col1Schema);
export { Col1 }

import { Col2Schema } from './schema.js';
const Col2 = new Mongo.Collection("col2");
      Col2.attachSchema(Col2Schema);
export { Col2 }
```

**Schema:**
```javascript
import {SimpleSchema} from 'meteor/aldeed:simple-schema';


export const Col1Schema = new SimpleSchema({
    text: { type: String },
    joinId: { type: String, optional: true }
});

export const Col2Schema = new SimpleSchema({
    text: { type: String }
})
```

**Links:**
```javascript
import { Col1 } from './collection.js';
import { Col2 } from './collection.js';

Col1.addLinks({
  col2: {
      type: 'one',
      collection: Col2,
      field: 'joinId',
      index: true
  }
});
```

**Exposures:**
```javascript
import { Col1 } from './collection.js';
import { Col2 } from './collection.js';

Col1.expose();
Col2.expose();
```

**Named Query**
```javascript
import { createNamedQuery } from 'meteor/cultofcoders:grapher';

export const testquery = createNamedQuery('testQuery',{
    col1: {
        text: 1,
        col2: {
          text: 1
        }
    }
});

if (Meteor.isServer) {
    testquery.expose()
}
```

**Comment by theodorDiaconu** [comment]
@samoilis write a quick reproduction repo. Any type of _id's should work. Grapher is agnostic wether it's a string or ObjectId

**Comment by samoilis** [comment]
To reproduce the problem use **grapher-boilerplate** and change the type of _ids from Posts collection and the postId from Comments collection

I've try to recreate the db with idGeneration="MONGO" option in the collection def but return me some errors: 
```
W20170301-21:41:59.862(2)? (STDERR) Error: After filtering out keys not in the schema, your object is now empty
W20170301-21:41:59.862(2)? (STDERR)     at [object Object].doValidate (packages/aldeed_collection2-core.js:416:11)
W20170301-21:41:59.862(2)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
W20170301-21:41:59.862(2)? (STDERR)     at imports/startup/server/fixtures.js:33:38
W20170301-21:41:59.863(2)? (STDERR)     at Array.map (native)
W20170301-21:41:59.863(2)? (STDERR)     at imports/startup/server/fixtures.js:33:21
W20170301-21:41:59.863(2)? (STDERR)     at Function.time (/home/manolis/www/grapher-boilerplate/.meteor/local/build/programs/server/profile.js:309:28)
W20170301-21:41:59.863(2)? (STDERR)     at /home/manolis/www/grapher-boilerplate/.meteor/local/build/programs/server/boot.js:312:13
W20170301-21:41:59.864(2)? (STDERR)     at /home/manolis/www/grapher-boilerplate/.meteor/local/build/programs/server/boot.js:353:5
W20170301-21:41:59.864(2)? (STDERR)     at Function.run (/home/manolis/www/grapher-boilerplate/.meteor/local/build/programs/server/profile.js:510:12)
W20170301-21:41:59.864(2)? (STDERR)     at /home/manolis/www/grapher-boilerplate/.meteor/local/build/programs/server/boot.js:351:11
```

after that I've create the collections with some data manually 

**the result is the same:** when the key field is ObjectId the Grapher does not return child objects 

-------------
Here is a sample from grapher-live:

**query:**
```
    users: {
        emails: 1,
        comments: {
            text: 1
        },
        posts: {
            title: 1,
            comments: {
                text: 1
            }
        }
    }
```

**result:**
```
[
	{
		"_id": "DZL84yDdr65s3XapK",
		"emails": [
			{
				"address": "admin@app.com",
				"verified": false
			}
		]
	},
	{
		"_id": "SBEesTdX764952c7c",
		"emails": [
			{
				"address": "user-1@app.com",
				"verified": false
			}
		],
		"comments": [
			{
				"text": "Good",
				"_id": {
					"_bsontype": "ObjectID",
					"id": {
						"0": 88,
						"1": 182,
						"2": 197,
						"3": 255,
						"4": 56,
						"5": 7,
						"6": 43,
						"7": 42,
						"8": 21,
						"9": 157,
						"10": 80,
						"11": 39
					}
				}
			}
		],
		"posts": [
			{
				"title": "User Post - 0",
				"_id": {
					"_bsontype": "ObjectID",
					"id": {
						"0": 88,
						"1": 182,
						"2": 197,
						"3": 116,
						"4": 56,
						"5": 7,
						"6": 43,
						"7": 42,
						"8": 21,
						"9": 157,
						"10": 80,
						"11": 33
					}
				}
			}
		]
	}
]
```

Because my project is new, I decide to change the IDs to string format (Meteor way), but I think this is a issue that will employ you in the future.

**Comment by theodorDiaconu** [comment]
@samoilis why do you say it doesn't fetch the children ? In your example it looks like it does. What you are seeing there is the serialization of ObjectId.

**Comment by theodorDiaconu** [comment]
Come to think of it. I realize now that using ObjectId's opens a can of worms. I'm sorry but I don't think we can fix this. At least, not until Grapher gets some good funding and at least 2-3 FT devs on it 🗡
