### ISSUE TITLE
«Error: Did not check() all arguments during call»

### ISSUE THREAD

**Issue by nadeemja** [cult-of-coders/grapher#193]
Hi,

I just read all the docs, and I'm so excited finally using grapher. However, I've got a problem. I can't get named queries to work.

Here is what I'm doing:

# The Code

`````
// imports/api/questions/index.js

import questionsForScheduleQuery from './questions_for_schedule';

export default { questionsForScheduleQuery };
`````

`````
// imports/api/questions/questions_for_schedule';

import Questions from '../../../lib/collections/questions';

export default Questions.createQuery('questionsForSchedule', {
  body: 1,
});
`````

`````
// server/grapher/questions/questions_for_schedule.js

import queries from '../../../imports/api/questions';
const { questionsForScheduleQuery } = queries;
questionsForScheduleQuery.expose();
`````

`````
// Client-side

import queries from '../../../imports/api/questions';
const { questionsForScheduleQuery } = queries;
questionsForScheduleQuery.clone().fetch((error, questions) => {
  console.log(error);
});

`````

# The Error
`````

I20171202-18:59:51.242(1)? Exception while invoking method 'named_query_questionsForSchedule' Error: Did not check() all arguments during call to 'named_query_questionsForSchedule'
I20171202-18:59:51.243(1)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check.js:483:13)
I20171202-18:59:51.243(1)?     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:131:16)
I20171202-18:59:51.244(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
I20171202-18:59:51.244(1)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20171202-18:59:51.244(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171202-18:59:51.244(1)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20171202-18:59:51.244(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171202-18:59:51.245(1)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20171202-18:59:51.245(1)?     at new Promise (<anonymous>)
I20171202-18:59:51.245(1)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20171202-18:59:51.245(1)?     at packages/meteorhacks_kadira.js:2619:38
I20171202-18:59:51.245(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
I20171202-18:59:51.246(1)?     at Session.sessionProto.protocol_handlers.method (packages/meteorhacks_kadira.js:2618:44)
I20171202-18:59:51.246(1)?     at packages/ddp-server/livedata_server.js:559:43
`````

**Comment by nadeemja** [comment]
Just found #73. The error goes aways when I ran `meteor remove audit-argument-checks`.

This doesn't appear to be a good practice from a security perspective.

Is there a way to support audit-argument-checks?

**Comment by theodorDiaconu** [comment]
@nadeemja yes. I think I can just run the check inside the exposed methods. And that would be it.

**Comment by theodorDiaconu** [comment]
You can leave it disabled for now to play with it, by the end of next week it'll be fixed.

**Comment by nadeemja** [comment]
Cool, thanks :)

**Comment by kratam** [comment]
Is it still required to disable audit-argument-checks?
