### ISSUE TITLE
$regex in $filters not working in subscribeCount

### ISSUE THREAD

**Issue by stefanholzapfel** [cult-of-coders/grapher#228]
Hi!

I always get  

> Exception while invoking method 'exposure_task.count.subscribe' MinimongoError: Key $regex must not start with '$'

on server when using a regex filter in a count subscription. Same filter in normal subscription is working.

Anybody else experiencing that issue?
Thanks!

**Comment by stefanholzapfel** [comment]
Some more information:

The parameters object I pass into the createQuery method before subscribe()
```
{
  $filters: {
    title: {
      $regex: "(?=.*Test.*)",
      $options: "i"
    }
  }
  $options: {
      limit: 30
      skip: 0
      sort: {
        start: 1
      }
  customer: {
    name: 1
    name2: 1
  }
  description: 1
  end: 1
  start: 1
  status: 1
  title: 1
  user: {
    username: 1
  }
}
```

The query I call is an exposed global query. Without regex the count works.

The full stacktrace on the server is:

```
Exception while invoking method 'exposure_task.count.subscribe' MinimongoError: Key $regex must not start with '$'
     at MinimongoError (packages/minimongo/common.js:1087:17)
     at assertIsValidFieldName (packages/minimongo/local_collection.js:1883:11)
     at Object.JSON.stringify (packages/minimongo/local_collection.js:1874:7)
     at JSON.stringify (<anonymous>)
     at assertHasValidFieldNames (packages/minimongo/local_collection.js:1873:10)
     at LocalCollection.insert (packages/minimongo/local_collection.js:94:5)
     at LocalCollection.<anonymous> (packages\matb33_collection-hooks.js:395:18)
     at LocalCollection.collection.(anonymous function) [as insert] (packages\matb33_collection-hooks.js:146:21)
     at ns.Collection.insert (packages/mongo/collection.js:515:39)
     at MethodInvocation.exposure_task.count.subscribe (packages/cultofcoders:grapher/lib/query/counts/genEndpoint.server.js:28:38)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:26)
     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:26)
     at Promise (packages/ddp-server/livedata_server.js:715:46)
     at new Promise (<anonymous>)
     at Session.method (packages/ddp-server/livedata_server.js:689:23)
     at packages/ddp-server/livedata_server.js:559:43
 Exception from sub exposure_task.count id W6eS2qH7dMsqJDDYq Error: Match error: Expected string, got null
     at check (packages/check/match.js:35:15)
     at Subscription.<anonymous> (packages/cultofcoders:grapher/lib/query/counts/genEndpoint.server.js:39:9)
     at packages\matb33_collection-hooks.js:307:21
     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:26)
     at Subscription._handler (packages\matb33_collection-hooks.js:306:28)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1043:15)
     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:26)
     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
     at packages/ddp-server/livedata_server.js:559:43
 Sanitized and reported to the client as: Match failed [400]
```

On the client there is no error.

**Comment by stefanholzapfel** [comment]
@theodorDiaconu Hi Theodor!
Do you think this bug can be fixed anytime soon? Our company is making a decision about the datalyer in the next weeks and I'm trying to convince everybody about the advantages of Grapher compared to a in-house development. This bug is the last issue that would prevent production use in our app.

Thanks for your support, I love working with Grapher so far!

**Comment by theodorDiaconu** [comment]
Hi @stefanholzapfel yes, this week I have 3 days booked for open-source :) So it will be fixed along with all the other bugs for sure! Thank you

**Comment by theodorDiaconu** [comment]
@stefanholzapfel 
```
export const postsQuery3 = createQuery('counts_posts_query3', {
    counts_posts: {
        $filters: {
            text: {
                $regex: 'text',
                $options: 'i',
            },
        },
        _id: 1,
        text: 1,
    },
});
```

I have this query which I expose, I can properly get the count for it. I want to break the functioanlity first with a test, but it seems I can't

**Comment by stefanholzapfel** [comment]
Works as expected now, thanks!
