### ISSUE TITLE
.addLinks is not a function

### ISSUE THREAD

**Issue by ntoka** [cult-of-coders/grapher#256]
Hey, I've created a separate file for linking and tried to add a simple link, but keep getting this issue:
`W20180530-17:07:49.014(3)? (STDERR) TypeError: Orders.addLinks is not a function
W20180530-17:07:49.014(3)? (STDERR)     at links.js (imports/api/lib/links.js:3:8)
W20180530-17:07:49.015(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180530-17:07:49.016(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180530-17:07:49.017(3)? (STDERR)     at main.js (server/main.js:1:349)
W20180530-17:07:49.017(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20180530-17:07:49.018(3)? (STDERR)     at require (packages\modules-runtime.js:238:16)1`

My links.js looks like this:
`import Customers from './collections/customers.js';
import Orders from './collections/orders.js';

Orders.addLinks({
    'customer': {
        type: 'one',
        collection: Customers,
        field: 'customer_id',
    }
});`

links.js file is imported on server after all collections.

Any ideas on what can be wrong? 
Thanks in advance!

**Comment by ntoka** [comment]
I was importing the collections incorrectly - needed to be e.g. 
import {Customers} from './collections/customers.js
