### ISSUE TITLE
$options in reducer body makes the query crash

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#304]
If you define a reducer and you want to sort the data before getting it, it fails:

```js
Links.addReducers({
  reducer3: {
    body: { title: 1, $options: { sort: { createdAt: -1 } } },
    reduce: ({ title }) => title // 
  }
});
```

This reducer was defined on the server, and after you run a query with this reducer on the client you see the following error:

```sh
I20181022-10:52:42.326(2)? Exception while invoking method 'named_query_myQuery2' TypeError: Cannot read property 'sort' of undefined
I20181022-10:52:42.326(2)?     at results.map.result (packages/cultofcoders:grapher/lib/query/reducers/lib/cleanReducerLeftovers.js:59:58)
I20181022-10:52:42.326(2)?     at Array.map (<anonymous>)
I20181022-10:52:42.326(2)?     at cleanNestedFields (packages/cultofcoders:grapher/lib/query/reducers/lib/cleanReducerLeftovers.js:59:38)
I20181022-10:52:42.327(2)?     at cleanNestedFields (packages/cultofcoders:grapher/lib/query/reducers/lib/cleanReducerLeftovers.js:59:5)
I20181022-10:52:42.327(2)?     at _.each.node (packages/cultofcoders:grapher/lib/query/reducers/lib/cleanReducerLeftovers.js:21:13)
I20181022-10:52:42.327(2)?     at Array.forEach (<anonymous>)
I20181022-10:52:42.327(2)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20181022-10:52:42.327(2)?     at cleanReducerLeftovers (packages/cultofcoders:grapher/lib/query/reducers/lib/cleanReducerLeftovers.js:19:7)
I20181022-10:52:42.327(2)?     at module.exportDefault (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:14:5)
I20181022-10:52:42.327(2)?     at hypernovaInit (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:27:5)
I20181022-10:52:42.328(2)?     at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:18:16)
I20181022-10:52:42.328(2)?     at Object.fetch (packages/cultofcoders:grapher/lib/namedQuery/namedQuery.server.js:38:26)
I20181022-10:52:42.328(2)?     at MethodInvocation.named_query_myQuery2 (packages/cultofcoders:grapher/lib/namedQuery/expose/extension.js:106:46)
I20181022-10:52:42.328(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20181022-10:52:42.328(2)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20181022-10:52:42.328(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
```

Here's a reproducible example: https://github.com/Floriferous/grapher-playground

**Comment by theodorDiaconu** [comment]
@Floriferous I don't want to allow $options or $filters at reducers level. The most I can do is throw an exception if such fields are found in reducer body.

**Comment by Floriferous** [comment]
Good tradeoff, makes it clearer indeed!

**Comment by theodorDiaconu** [comment]
@Floriferous I remembered that it's a bad trade-off. For example, let's say you want "lastInvoice" as a reducer and you want to apply a limit:1 and sort createdAt:-1. I managed to fix the issue. It was a simple fix. But this is useful. Though at some point it may cause some confusions if people use multiple reducers that link with the same collection.

**Comment by Floriferous** [comment]
So you're sayig you _did_ allow $options and $filters in the reducers?

**Comment by theodorDiaconu** [comment]
Yes. I managed to fix the issue in the cleaning up phase.
