### ISSUE TITLE
Multiple insert of empty many-to-one links fails

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#310]
When trying to insert a many-to-one-unique link multiple times without adding a link, it fails with the following error:

```js
B.addLinks({
  C: {
    field: 'cLinks',
    collection: C,
    type: 'many',
    metadata: true,
    unique: true
  },
});

C.addLinks({
  B: {
    collection: B,
    inversedBy: 'C'
  }
});

  describe('insert', () => {
    it('fails', () => {
      const id1 = B.insert({});
      const id2 = B.insert({});
    });
  });
```

```sh
BulkWriteError: E11000 duplicate key error collection: meteor.b index: cLinks._id_1 dup key: { : null }
I20181024-14:04:06.744(2)?       at OrderedBulkOperation.handleWriteError (/Users/Florian/.meteor/packages/npm-mongo/.3.1.1.1s4wr2v.l5o9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/common.js:1048:11)
I20181024-14:04:06.744(2)?       at resultHandler (/Users/Florian/.meteor/packages/npm-mongo/.3.1.1.1s4wr2v.l5o9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/bulk/ordered.js:159:23)
I20181024-14:04:06.752(2)?       at /Users/Florian/.meteor/packages/npm-mongo/.3.1.1.1s4wr2v.l5o9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:532:18
I20181024-14:04:06.752(2)?       at _combinedTickCallback (internal/process/next_tick.js:131:7)
I20181024-14:04:06.752(2)?       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Here's a reproduction: https://github.com/Floriferous/grapher-playground (branch: `unique-insert-null`)

**Comment by theodorDiaconu** [comment]
@Floriferous because it automatically adds uniqueness index to the field... it makes sense. How do you think we should solve this ?

**Comment by Floriferous** [comment]
Yeah, I get where the index comes from. But I don't really understand how uniqueness and indices work, can't there be an exception for null indices?

**Comment by theodorDiaconu** [comment]
Yes. ```{unique: true, sparse: true}``` this. Will be added and checked.
