### ISSUE TITLE
Nested query fails when one of the nested items does not exist

### ISSUE THREAD

**Issue by Floriferous** [cult-of-coders/grapher#340]
Here's some code that throws (and a reproduction, but it's essentially the same: https://github.com/Floriferous/grapher-playground/tree/undefined-link). The error is hard to understand, it would be better if it simply ignored documents that don't exist in the DB.

```js
import { expect } from 'chai';
import { Mongo } from 'meteor/mongo';

const A = new Mongo.Collection('a');
const B = new Mongo.Collection('b');
const C = new Mongo.Collection('c');

A.addLinks({
  b: {
    field: 'bLinks',
    collection: B,
    type: 'many',
    metadata: true
  }
});

B.addLinks({
  a: {
    collection: A,
    inversedBy: 'b'
  },
  c: {
    collection: C,
    inversedBy: 'b'
  }
});

C.addLinks({
  b: {
    field: 'bLinks',
    collection: B,
    type: 'many',
    metadata: true
  }
});

describe('links', () => {
  it('should not throw when an unknown id is set as a link', () => {
    const bId = B.insert({});
    const cId = C.insert({ bLinks: [{ _id: 'unknownId' }, { _id: bId }] });

    const result = C.createQuery({
      b: {
        a: {
          _id: 1
        }
      }
    }).fetchOne(); // Throws, because there is no "b" with _id 'unknownId'

    expect(result).to.not.equal(undefined);
  });
});
```

The error:
```sh
I20190213-15:45:25.570(1)?      TypeError: Cannot read property 'a' of undefined
I20190213-15:45:25.571(1)?       at _.each.result (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:125:51)
I20190213-15:45:25.571(1)?       at Array.forEach (<anonymous>)
I20190213-15:45:25.571(1)?       at Function._.each._.forEach (packages/underscore.js:139:11)
I20190213-15:45:25.571(1)?       at node.collectionNodes.forEach.collectionNode (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:124:11)
I20190213-15:45:25.571(1)?       at Array.forEach (<anonymous>)
I20190213-15:45:25.571(1)?       at storeOneResults (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:123:26)
I20190213-15:45:25.571(1)?       at _.each.result (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:125:13)
I20190213-15:45:25.571(1)?       at Array.forEach (<anonymous>)
I20190213-15:45:25.571(1)?       at Function._.each._.forEach (packages/underscore.js:139:11)
I20190213-15:45:25.572(1)?       at node.collectionNodes.forEach.collectionNode (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:124:11)
I20190213-15:45:25.572(1)?       at Array.forEach (<anonymous>)
I20190213-15:45:25.572(1)?       at storeOneResults (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:123:26)
I20190213-15:45:25.572(1)?       at module.exportDefault (packages/cultofcoders:grapher/lib/query/lib/prepareForDelivery.js:12:5)
I20190213-15:45:25.572(1)?       at hypernovaInit (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:27:5)
I20190213-15:45:25.572(1)?       at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:18:16)
I20190213-15:45:25.572(1)?       at Query.fetchOne (packages/cultofcoders:grapher/lib/query/query.server.js:26:29)
```

**Comment by Floriferous** [comment]
@theodorDiaconu Can you look into this?
