### ISSUE TITLE
ERROR Expose Unknown key in field maxLimit,publication,method,blocking,maxDepth 

### ISSUE THREAD

**Issue by mahadoang** [cult-of-coders/grapher#344]
METEOR@1.8.0.2
cultofcoders:grapher@1.3.9_1

items.js
```

import Conversation from './collection';
import Customer from '../customer/collection';

Conversation.addLinks({
    'customer': {
    	type: 'one',
        field: 'customer_id',
        collection: Customer
    }
});

export default Conversation.createQuery('converation_items', 
{
    $postOptions: 
    {
        limit:250,
        sort: 
        {
            'is_pinned':-1,
            'last_updated': -1,
        },
    },
    created_at: 1,
    source_name:1,
    unread_message:1,
    last_message:1,
    last_updated:1,
    is_pinned:1,
    customer:{
        full_name:1,
        avatar:1
    }
});
```

items.expose.js
```
import { Meteor } from 'meteor/meteor';
import itemsQuery from './items';
import _ from 'lodash';

itemsQuery.expose({

    firewall(filters, options, userId) 
    {
        console.log(options);
        if (!userId) { throw new Meteor.Error('Please Login');}
        filters.completed   = false;
    },
    maxLimit: 250, 
    publication: true,
    method: false,
    blocking: false,
    maxDepth: 2,
});
```

Display Error
```
W20190309-01:15:35.306(7)? (STDERR) /Users/mahadoang/.meteor/packages/meteor-tool/.1.8.0_2.58iyz7.mvyce++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190309-01:15:35.306(7)? (STDERR)                                             throw(ex);
W20190309-01:15:35.306(7)? (STDERR)                                             ^
W20190309-01:15:35.516(7)? (STDERR) Error: Match error: Unknown key in field maxLimit
W20190309-01:15:35.516(7)? (STDERR)     at check (packages/check/match.js:36:17)
W20190309-01:15:35.516(7)? (STDERR)     at Object.expose (packages/cultofcoders:grapher/lib/namedQuery/expose/extension.js:32:9)
W20190309-01:15:35.517(7)? (STDERR)     at expose.js (src/imports/api/chats/conversation/expose.js:5:12)
W20190309-01:15:35.517(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190309-01:15:35.517(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190309-01:15:35.517(7)? (STDERR)     at Module.moduleLink [as link] (/Users/mahadoang/.meteor/packages/modules/.0.13.0.1aurolz.v3oz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190309-01:15:35.517(7)? (STDERR)     at index.js (src/imports/api/chats/conversation/index.js:1:33)
W20190309-01:15:35.518(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190309-01:15:35.518(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190309-01:15:35.518(7)? (STDERR)     at Module.moduleLink [as link] (/Users/mahadoang/.meteor/packages/modules/.0.13.0.1aurolz.v3oz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190309-01:15:35.518(7)? (STDERR)     at index.js (src/imports/services/index.js:1:516)
W20190309-01:15:35.519(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190309-01:15:35.519(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190309-01:15:35.519(7)? (STDERR)     at Module.moduleLink [as link] (/Users/mahadoang/.meteor/packages/modules/.0.13.0.1aurolz.v3oz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190309-01:15:35.519(7)? (STDERR)     at index.js (src/imports/startup/server/index.js:1:363)
W20190309-01:15:35.519(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
```
Please Help me.
Thank you.

**Comment by theodorDiaconu** [comment]
Global exposure is different from named query exposure.

Read the API this is what's available:
https://github.com/cult-of-coders/grapher/blob/master/docs/api.md#exposing-named-queries
