### ISSUE TITLE
Query.clone() on Server - MongoError: Cursor is closed

### ISSUE THREAD

**Issue by Twisterking** [cult-of-coders/grapher#353]
So I am running into a weird error:

I've got my main app running on `localhost:3000`, which is also running the mongo server.
On `localhost:3030` with `MONGO_URL=mongodb://127.0.0.1:3001/meteor` I am running my new cordova-meteor-app in development - so this is just running in the browser on port 3030, which being connected to the main mongo server.

On the client everything is fine, but if I want to `clone()` a named query on the server and `fetch()` it, I always end up with this error:

```bash
I20190425-13:06:40.821(2)? Exception while invoking method 'placeOpenOrder' { MongoError: Cursor is closed
I20190425-13:06:40.822(2)?     at Function.create (/Users/patrick/.meteor/packages/npm-mongo/.3.1.2.hrnmxu.plt7g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:43:12)
I20190425-13:06:40.822(2)?     at AggregationCursor.Cursor.filter (/Users/patrick/.meteor/packages/npm-mongo/.3.1.2.hrnmxu.plt7g++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cursor.js:266:22)
I20190425-13:06:40.822(2)?     at parentResults.forEach.parentResult (packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:69:63)
I20190425-13:06:40.822(2)?     at Array.forEach (<anonymous>)
I20190425-13:06:40.822(2)?     at packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:67:23
I20190425-13:06:40.822(2)?     at storeHypernovaResults (packages/cultofcoders:grapher/lib/query/hypernova/storeHypernovaResults.js:59:9)
I20190425-13:06:40.822(2)?     at _.each.childCollectionNode (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:9:9)
I20190425-13:06:40.823(2)?     at Array.forEach (<anonymous>)
I20190425-13:06:40.825(2)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20190425-13:06:40.826(2)?     at hypernova (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:6:7)
I20190425-13:06:40.826(2)?     at _.each.childCollectionNode (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:10:9)
I20190425-13:06:40.826(2)?     at Array.forEach (<anonymous>)
I20190425-13:06:40.826(2)?     at Function._.each._.forEach (packages/underscore.js:139:11)
I20190425-13:06:40.826(2)?     at hypernova (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:6:7)
I20190425-13:06:40.826(2)?     at hypernovaInit (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:25:5)
I20190425-13:06:40.826(2)?     at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:18:16)
I20190425-13:06:40.826(2)?     at Object.fetch (packages/cultofcoders:grapher/lib/namedQuery/namedQuery.server.js:38:2
```

Anybody has any ideas on this?

**On the main server (`locahost:3000`) doing exactly the same works just fine.**

any solution for this?

**UPDATE:**

So I turns out it has something to do with a subquery. I tried basically copy/pasting the exact same query:

```js
      myOpenOrdersQuery = OpenOrdersBody.createQuery({
        $filter({filters, options, params}) {
          filters.list_id = openOrderId;
        },
        _id: 1,
        list_id: 1,
        row_id: 1,
        item_amount: 1,
        unit: 1,
        total_price: 1,
        item: {
          supplier_id: 1,
          item_ref: 1,
          item_name: 1,
          unit: 1,
          units: 1,
          price: 1,
          image_id: 1,
          image_url: 1,
          // prices: { // <-- as soon as I use this subquery, the "Cursor is closed" Error occurs.
          //   $filters: {
          //     $or: pricesOr
          //   },
          //   itemId: 1,
          //   userId: 1,
          //   groupId: 1,
          //   priceInfo: 1
          // },
          meta: 1
        },
        $options: {
          sort: { row_id: 1 }
        }
      });
```
So my subquery "prices" is for some reason the problem, but I don't understand why.

**Comment by theodorDiaconu** [comment]
I have no idea why a cursor would just close? Can you help me reproduce it ?

**Comment by shaunstoltz** [comment]
Have the same issue linking a collection to itself in a parent/child fashion using inversedby to get the children from the parent.

https://stackoverflow.com/questions/23915967/mongodb-nodejs-native-cursor-closing-prematurely

Seems this is a known issue?

**Comment by theodorDiaconu** [comment]
@shaunstoltz it may be. but I doubt it's related with the linking of collections. I need reproduction
