### ISSUE TITLE
publish composite error with Grapher

### ISSUE THREAD

**Issue by flean** [cult-of-coders/grapher#366]
Not sure why this is happening, I can't find where this is happening, any tips on how to find the issue?

`
pz4cm
2019-06-21 10:55:22-07:00Exception in callback of async function: Error: Doc not found in list: mDstnCaXj6MD77eds
pz4cm
2019-06-21 10:55:22-07:00 at PublishedDocumentList.addChildPub (packages/reywood:publish-composite/lib/published_document_list.js:26:19)
pz4cm
2019-06-21 10:55:22-07:00 at Publication.createChildPublication (packages/reywood:publish-composite/lib/publication.js:117:32)
pz4cm
2019-06-21 10:55:22-07:00 at Array.forEach (<anonymous>)
pz4cm
2019-06-21 10:55:22-07:00 at Function._.each._.forEach (packages/underscore.js:139:11)
pz4cm
2019-06-21 10:55:22-07:00 at Publication._publishChildrenOf (packages/reywood:publish-composite/lib/publication.js:115:11)
pz4cm
2019-06-21 10:55:22-07:00 at observeHandle.cursor.observe.added.Meteor.bindEnvironment.doc (packages/reywood:publish-composite/lib/publication.js:54:26)
pz4cm
2019-06-21 10:55:22-07:00 at runWithEnvironment (packages/meteor.js:1286:24)
pz4cm
2019-06-21 10:55:22-07:00 at Object.added (packages/meteor.js:1299:14)
pz4cm
2019-06-21 10:55:22-07:00 at _CachingChangeObserver.added (packages/minimongo/local_collection.js:1305:28)
pz4cm
2019-06-21 10:55:22-07:00 at added (packages/minimongo/local_collection.js:707:29)
pz4cm
2019-06-21 10:55:22-07:00 at runWithEnvironment (packages/meteor.js:1286:24)
pz4cm
2019-06-21 10:55:22-07:00 at packages/meteor.js:1299:14
pz4cm
2019-06-21 10:55:22-07:00 at packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:256:18
pz4cm
2019-06-21 10:55:22-07:00 at _IdMap.forEach (packages/id-map/id-map.js:51:35)
pz4cm
2019-06-21 10:55:22-07:00 at ObserveMultiplexer._sendAdds (packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:249:26)
pz4cm
2019-06-21 10:55:22-07:00 at ObserveMultiplexer.kadira_Multiplexer_sendAdds [as _sendAdds] (packages/mdg:meteor-apm-agent/lib/hijack/set_labels.js:18:29)
pz4cm
2019-06-21 10:55:22-07:00 at packages/cultofcoders:redis-oplog/lib/mongo/ObserveMultiplex.js:68:18
pz4cm
2019-06-21 10:55:22-07:00 at runWithEnvironment (packages/meteor.js:1286:24)
pz4cm
2019-06-21 10:55:22-07:00 at Object.task (packages/meteor.js:1299:14)
pz4cm
2019-06-21 10:55:22-07:00 at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
pz4cm
2019-06-21 10:55:22-07:00 at packages/meteor.js:894:12`

**Comment by theodorDiaconu** [comment]
@flean create a reproduction please.
