### ISSUE TITLE
audit-argument-checks and Global Exposure

### ISSUE THREAD

**Issue by DDynamic** [cult-of-coders/grapher#370]
Hello,
Thank you so much for this package! I am wondering if it is possibly to satisfy `audit-argument-checks` when using global exposure.

```javascript
// server
Meteor.users.expose({
    firewall(filters, options, userId) {
      check(filters._id, String);
      check(options, Object);
      check(userId, String);
    }
  });

// client
const query = Meteor.users.createQuery({
      $filters: { _id: FlowRouter.getParam('_id') },
      memberId: 1,
      member: {
        membershipStarted: 1
      }
    });

    query.subscribe();
    return query.fetchOne();
  }
```

This is the error I am getting:
```
Exception from sub exposure_users id 7p... Error: Did not check() all arguments during publisher 'exposure_users'
I20190729-16:02:25.951(-5)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
I20190729-16:02:25.951(-5)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
I20190729-16:02:25.952(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
I20190729-16:02:25.952(-5)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
I20190729-16:02:25.952(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20190729-16:02:25.953(-5)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
I20190729-16:02:25.953(-5)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
I20190729-16:02:25.953(-5)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
I20190729-16:02:25.954(-5)?     at packages/ddp-server/livedata_server.js:559:43
I20190729-16:02:25.990(-5)? Exception from sub exposure_users id e5... Error: Did not check() all arguments during publisher 'exposure_users'
I20190729-16:02:26.004(-5)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
I20190729-16:02:26.004(-5)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
I20190729-16:02:26.004(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:18)
I20190729-16:02:26.005(-5)?     at DDP._CurrentPublicationInvocation.withValue (packages/ddp-server/livedata_server.js:1046:15)
I20190729-16:02:26.005(-5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20190729-16:02:26.005(-5)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1044:51)
I20190729-16:02:26.006(-5)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:860:9)
I20190729-16:02:26.006(-5)?     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
```

Please let me know if there is any more information or code samples I can provide. Thanks in advance for your help.

**Comment by LordA98** [comment]
Hi @DDynamic,

Did you ever figure this out?

[This closed post](https://github.com/cult-of-coders/grapher/issues/193) suggests `audit-argument-checks` package needs to be removed entirely - that it can be used with Grapher.

@theodorDiaconu, is it possible to use audit-argument-checks with Grapher?  I'm also receiving the same error.
