### ISSUE TITLE
Incompatible with 1.8.2? TypeError: collection.getLinker is not a function

### ISSUE THREAD

**Issue by janat08** [cult-of-coders/grapher#407]
I don't think this is related to: https://github.com/cult-of-coders/grapher/issues/174

My links.js. Which is imported into startup/server, beneath collection imports. I don't see how this produce circular dependencies (and they were suppose to be fixed anyway according to the linked issue above).
```
import Products from './products/products.js'
import {ImagesCollection, ImagesFiles} from './images/images.js'
import {Carts} from './carts/carts.js'

console.log(typeof Carts, typeof ImagesCollection, typeof Products, 322)
ImagesCollection.addLinks({
    'products': {
        collection: Products,
        inversedBy: 'images'
    }
})

Products.addLinks({
    'images': {
        type: 'many',
        collection: ImagesCollection,
        field: 'meta.imageIds',
    }
})

Carts.addLinks({
    "productsLink": {
        collection: Products,
        type: "many",
        field: "products",
    }
})

Products.addLinks({
    carts: {
        collection: Carts,
        inversedBy: 'images'
    }
})
```

I get error: 
```
W20191201-10:47:17.740(0)? (STDERR) TypeError: collection.getLinker is not a function
W20191201-10:47:17.741(0)? (STDERR)     at Linker._prepareVirtual (packages/cultofcoders:grapher/lib/links/linker.js:196:33)
W20191201-10:47:17.741(0)? (STDERR)     at Linker._validateAndClean (packages/cultofcoders:grapher/lib/links/linker.js:167:25)
W20191201-10:47:17.742(0)? (STDERR)     at new Linker (packages/cultofcoders:grapher/lib/links/linker.js:24:14)
W20191201-10:47:17.743(0)? (STDERR)     at _.each (packages/cultofcoders:grapher/lib/links/extension.js:23:28)
W20191201-10:47:17.744(0)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20191201-10:47:17.745(0)? (STDERR)     at ns.Collection.addLinks (packages/cultofcoders:grapher/lib/links/extension.js:14:11)
W20191201-10:47:17.745(0)? (STDERR)     at links.js (imports/api/links.js:6:18)
W20191201-10:47:17.751(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20191201-10:47:17.752(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20191201-10:47:17.753(0)? (STDERR)     at Module.moduleLink [as link] (/home/ubuntu/.meteor/packages/modules/.0.14.0.a0sh8b.5x5us++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20191201-10:47:17.753(0)? (STDERR)     at index.js (imports/startup/server/index.js:1:162)
W20191201-10:47:17.754(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20191201-10:47:17.755(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20191201-10:47:17.756(0)? (STDERR)     at Module.moduleLink [as link] (/home/ubuntu/.meteor/packages/modules/.0.14.0.a0sh8b.5x5us++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20191201-10:47:17.756(0)? (STDERR)     at main.js (server/main.js:1:8)
```

**Comment by janat08** [comment]
Repo: https://github.com/janat08/meteorShoppingCart

**Comment by janat08** [comment]
and then if that error doesn't popup using boilerplate repo's code, then I get  
Error: Match error: Failed Match.Where validation in field collection

https://github.com/janat08/meteorShoppingCart/tree/ea2790ae11635335c753133ecec7307e09c51bee

**Comment by theodorDiaconu** [comment]
@janat08 can you please console.log your collectiosn before adding links? You have a recursive inter-dependency somewhere outside this code. Usually links.js is a separate file executed after all collections are loaded.

**Comment by theodorDiaconu** [comment]
If problem persists, please feel free to re-open and I will investigate shortly.

**Comment by janat08** [comment]
Ye I resolved the inter-dependency, Match error: https://github.com/janat08/meteorShoppingCart/blob/ea2790ae11635335c753133ecec7307e09c51bee/imports/api/grapher/index.js

**Comment by theodorDiaconu** [comment]
@janat08 can you paste me the full error ? or it is just cryptic? `Error: Match error: Failed Match.Where validation in field collection`

**Comment by janat08** [comment]
Its cryptic.

**Comment by theodorDiaconu** [comment]
I get this error:
```
I20191203-08:45:14.147(2)? RangeError: Maximum call stack size exceeded
I20191203-08:45:14.238(2)?     at Array.forEach (<anonymous>)
I20191203-08:45:14.238(2)?     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
I20191203-08:45:14.238(2)?     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
I20191203-08:45:14.238(2)?     at Array.forEach (<anonymous>)
I20191203-08:45:14.238(2)?     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
I20191203-08:45:14.238(2)?     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
I20191203-08:45:14.238(2)?     at Array.forEach (<anonymous>)
I20191203-08:45:14.239(2)?     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
I20191203-08:45:14.239(2)?     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
I20191203-08:45:14.239(2)?     at Array.forEach (<anonymous>)
I20191203-08:45:14.239(2)?     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
I20191203-08:45:14.239(2)?     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
I20191203-08:45:14.239(2)?     at Array.forEach (<anonymous>)
I20191203-08:45:14.239(2)?     at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
I20191203-08:45:14.239(2)?     at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
I20191203-08:45:14.239(2)?     at Array.forEach (<anonymous>) undefined
```

**Comment by janat08** [comment]
Are you using the latest master?
